[feat] Android 애플리케이션 추가
EATSTEAK/rusaint pull request #88
Opened 2024-08-22 09:08 UTC by cometj03

2024-08-22 09:12 UTC, cometj03 commented on languages/kotlin/lib/build.gradle.kts
> +        minSdk = 24
minSdk가 너무 높으면 minSdk가 낮은 프로젝트에서 사용할 수 없기 때문에 낮췄습니다

2024-08-22 09:14 UTC, cometj03 commented on languages/kotlin/lib/build.gradle.kts
> -    implementation("net.java.dev.jna:jna:5.14.0@aar")
5.13.0 이상으로 설정하면 앱 설치조차 안 되는 문제가 있어서 5.12.0으로 낮췄습니다

2024-08-25 11:16 UTC, EATSTEAK requested changes

2024-08-25 11:16 UTC, EATSTEAK commented on languages/kotlin/README.md
> +cargo install cross
`cross`는 한번만 설치하면 되고, 아래의 이전 리비전을 설치해야 하기 때문에 요부분은 지워주세요!

2024-08-25 11:16 UTC, EATSTEAK commented on languages/kotlin/README.md
> +./build-binginds.sh
여기 오타났네요. `build-bindings.sh`로 변경해주세요.

2024-08-25 11:16 UTC, EATSTEAK commented on languages/kotlin/app/src/main/kotlin/dev/eatsteak/rusaint/android/MainActivity.kt
> +                        CourseType.BACHELOR)
여기 아래에 `println(semesterGrades)`로 볼 수 있게끔 하면 좋을 것 같습니다~

2024-08-25 11:27 UTC, EATSTEAK requested changes

2024-08-25 11:27 UTC, EATSTEAK commented on languages/kotlin/README.md
> +./build-binding.sh
`./build-bindings.sh` 입니다!

2024-08-25 11:29 UTC, cometj03 commented on languages/kotlin/README.md
> +./build-binding.sh
앗 수정했습니다!

2024-08-25 11:30 UTC, EATSTEAK approved these changes

2024-08-25 11:30 UTC, merged