feat: iOS SDK 테스트 완료
EATSTEAK/rusaint pull request #92
Opened 2024-08-25 12:00 UTC by LeeJoEun-01

- 학기별 성적 불러오기 테스트 완료
<img src="https://github.com/user-attachments/assets/f777de0e-134d-42d6-9e1c-f7c224c4ef1f">

2024-08-25 14:00 UTC, EATSTEAK requested changes
각 conversation 참고해서 변경해주세요!

2024-08-25 17:04 UTC, LeeJoEun-01 commented
@EATSTEAK 코드리뷰 반영 했습니다~

2024-08-26 03:05 UTC, EATSTEAK requested changes

2024-08-26 03:05 UTC, EATSTEAK commented on languages/swift/Sources/Rusaint/.gitignore
`xcuserdata` 파일은 `languages/swift/Rusaint-iOS` 아래에 있는 파일인 만큼 `.gitignore` 파일은 해당 폴더에도 반영될 수 있게끔 `languages/swift/Rusaint-iOS/.gitignore` 파일을 새로 만들어서 넣어주세요!

그리고 이 `.gitignore` 파일은 `languages/swift/Sources/Rusaint` 폴더 아래에만 적용되고, 이 폴더에는 자동생성된 스위프트 파일이 들어갑니다. 그래서 자동생성된 파일을 제외하기 위해서 기존 내용이 있었던 거라 기존 내용은 복구해주세요~

2024-08-26 03:05 UTC, EATSTEAK commented on languages/swift/Sources/Rusaint/Rusaint.swift
`languages/swift/Sources/Rusaint/Rusaint.swift` 파일은 자동 생성된 파일이므로 포함되서는 안됩니다. 확인하시고 제거해주세요!

2024-08-26 03:05 UTC, EATSTEAK commented on languages/swift/Sources/Rusaint/RusaintBase.swift
`languages/swift/Sources/Rusaint/RusaintBase.swift` 파일은 자동 생성된 파일이므로 포함되서는 안됩니다. 확인하시고 제거해주세요!

2024-08-26 14:02 UTC, LeeJoEun-01 commented on languages/swift/Sources/Rusaint/RusaintBase.swift
넵! 다 확인해서 반영했습니다!!

2024-08-27 03:11 UTC, EATSTEAK requested changes

2024-08-27 03:11 UTC, EATSTEAK commented on languages/swift/Rusaint-iOS/Rusaint-iOS.xcodeproj/xcuserdata/joeun.xcuserdatad/xcschemes/xcschememanagement.plist
요거 삭제 안되어있어요!

2024-08-27 03:48 UTC, LeeJoEun-01 commented on languages/swift/Rusaint-iOS/Rusaint-iOS.xcodeproj/xcuserdata/joeun.xcuserdatad/xcschemes/xcschememanagement.plist
넵 삭제했습니다!!

2024-08-27 03:49 UTC, EATSTEAK approved these changes

2024-08-27 03:49 UTC, merged